cookie:
  expiry_days: 30
  key: cookie_key
  name: cookie_key_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: John Smith
      password: $2b$12$khDC/Acqw.2c5WFrdybPsuzmSEjLIeS7LNdua/hrYjODIuMLCIGlO
pre-authorized:
  emails:
  - test@gmail.com
